# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpc_evento', '0002_auto_20171023_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoraEntrada', models.DateTimeField()),
                ('HoraSaidaAlmoco', models.DateTimeField()),
                ('HoraRetornoAlmoco', models.DateTimeField()),
                ('HoraSaida', models.DateTimeField()),
                ('ipMaquina', models.CharField(max_length=15)),
                ('nomeChefe', models.CharField(max_length=128, null=True)),
                ('statusFrequencia', models.CharField(choices=[('IN', 'INCONSISTENTE'), ('CN', 'CONSISTENTE')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='Evento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='Participante',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='Ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='idEvento',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='situacaoFuncional',
            field=models.CharField(choices=[('ST', 'Estagiario'), ('SR', 'Servidor')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.AddField(
            model_name='frequenciadia',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Funcionario', to='lpc_evento.Pessoa'),
        ),
    ]
