# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpc_evento', '0003_auto_20171113_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciadia',
            name='justificativa',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
