# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpc_evento', '0004_frequenciadia_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenciadia',
            name='justificativa',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
